language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

before_install:
    # GCC update for linux, to ensure C++11 support.
  - if [ $TRAVIS_OS_NAME == linux ]; then
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
        sudo apt-get update -qq;
    fi

    # GLFW install on linux:
  - if [ $TRAVIS_OS_NAME == linux ]; then
        sudo add-apt-repository -y ppa:pyglfw/pyglfw;
        sudo apt-get update -qq;
        sudo apt-get install -y --no-install-recommends libglfw3-dev libxrandr-dev libxi-dev libxxf86vm-dev;
    fi

    # GLFW install on MacOS:
  - if [ $TRAVIS_OS_NAME == osx ]; then
        brew update;
        brew install glfw3;
    fi

install:
    # Finish the GCC install for linux:
  - if [ $TRAVIS_OS_NAME == linux ]; then
        sudo apt-get install -qq g++-5;
        export CXX="g++-5";
        export CC="gcc-5";
    fi

script:
  - $CXX --version
  - make -C samples

